version: '3.1'
services:
  rmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: jest-test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
